/**
 * Racines et expressions modérées par langue.
 *
 * - Termes ≤3 caractères : correspondance exacte (token ou pseudo entier compact).
 * - Termes ≥4 caractères : sous-chaîne sur la forme compacte (leet, espaces, séparateurs).
 *
 * Commentaires grave / moyen : tous bloqués pour l'instant ; le marquage partiel
 * pourra s'appuyer sur ModerationSeverity plus tard.
 */

import { foldDiacritics } from './normalize'

export type ModerationLocale = 'fr' | 'en' | 'es' | 'it'
export type ModerationSeverity = 'severe' | 'medium' | 'mild'

export type ModerationTermEntry = {
  term: string
  severity: ModerationSeverity
}

const FR_TERMS: readonly ModerationTermEntry[] = [
  { term: 'pute', severity: 'severe' },
  { term: 'putain', severity: 'severe' },
  { term: 'salope', severity: 'severe' },
  { term: 'salop', severity: 'severe' },
  { term: 'salaud', severity: 'severe' },
  { term: 'connard', severity: 'severe' },
  { term: 'connasse', severity: 'severe' },
  { term: 'conasse', severity: 'severe' },
  { term: 'konard', severity: 'severe' },
  { term: 'konar', severity: 'severe' },
  { term: 'konass', severity: 'severe' },
  { term: 'encul', severity: 'severe' },
  { term: 'enfoir', severity: 'severe' },
  { term: 'enfoire', severity: 'severe' },
  { term: 'enfoiré', severity: 'severe' },
  { term: 'merde', severity: 'severe' },
  { term: 'merd', severity: 'severe' },
  { term: 'sousmerd', severity: 'severe' },
  { term: 'sous merd', severity: 'severe' },
  { term: 'mangemerd', severity: 'severe' },
  { term: 'mange merd', severity: 'severe' },
  { term: 'niquetamere', severity: 'severe' },
  { term: 'nique ta mere', severity: 'severe' },
  { term: 'nique ta mère', severity: 'severe' },
  { term: 'niquer', severity: 'severe' },
  { term: 'nique', severity: 'severe' },
  { term: 'ntm', severity: 'severe' },
  { term: 'trouduc', severity: 'severe' },
  { term: 'trou du cul', severity: 'severe' },
  { term: 'trou du c', severity: 'severe' },
  { term: 'troudcul', severity: 'severe' },
  { term: 'cassecouille', severity: 'severe' },
  { term: 'casse couille', severity: 'severe' },
  { term: 'cassecouill', severity: 'severe' },
  { term: 'cass couill', severity: 'severe' },
  { term: 'petescouill', severity: 'severe' },
  { term: 'pete les couill', severity: 'severe' },
  { term: 'batard', severity: 'severe' },
  { term: 'bâtard', severity: 'severe' },
  { term: 'batar', severity: 'severe' },
  { term: 'filsdepute', severity: 'severe' },
  { term: 'fils de pute', severity: 'severe' },
  { term: 'fils d pute', severity: 'severe' },
  { term: 'fils2pute', severity: 'severe' },
  { term: 'fdp', severity: 'severe' },
  { term: 'fdph', severity: 'severe' },
  { term: 'bite', severity: 'severe' },
  { term: 'couille', severity: 'severe' },
  { term: 'couilles', severity: 'severe' },
  { term: 'couillon', severity: 'severe' },
  { term: 'pédé', severity: 'severe' },
  { term: 'pede', severity: 'severe' },
  { term: 'tapette', severity: 'severe' },
  { term: 'nègre', severity: 'severe' },
  { term: 'negre', severity: 'severe' },
  { term: 'nazi', severity: 'severe' },
  { term: 'hitler', severity: 'severe' },
  { term: 'branleur', severity: 'medium' },
  { term: 'branleuse', severity: 'medium' },
  { term: 'branl', severity: 'medium' },
  { term: 'grognasse', severity: 'medium' },
  { term: 'pouffiasse', severity: 'medium' },
  { term: 'poufiasse', severity: 'medium' },
  { term: 'poufias', severity: 'medium' },
  { term: 'tagueule', severity: 'medium' },
  { term: 'ta gueule', severity: 'medium' },
  { term: 'tgule', severity: 'medium' },
  { term: 'fermetagueule', severity: 'medium' },
  { term: 'ferme ta g', severity: 'medium' },
  { term: 'tg', severity: 'medium' },
  { term: 'raclure', severity: 'medium' },
  { term: 'salemerde', severity: 'medium' },
  { term: 'sale merd', severity: 'medium' },
  { term: 'salechienne', severity: 'medium' },
  { term: 'sale chienne', severity: 'medium' },
  { term: 'ta mere', severity: 'medium' },
  { term: 'tamer', severity: 'medium' },
  { term: 'tabarnak', severity: 'severe' },
  { term: 'tabarnac', severity: 'severe' },
  { term: 'calisse', severity: 'severe' },
  { term: 'câlice', severity: 'severe' },
  { term: 'calice', severity: 'severe' },
  { term: 'esti', severity: 'medium' },
  { term: 'crisse', severity: 'medium' },
  { term: 'criss', severity: 'medium' },
  { term: 'sacrament', severity: 'medium' },
  { term: 'sacrément', severity: 'medium' },
  { term: 'osti', severity: 'medium' },
  { term: 'ostie', severity: 'medium' },
  { term: 'ciboire', severity: 'medium' },
  { term: 'viarge', severity: 'medium' },
]

const EN_TERMS: readonly ModerationTermEntry[] = [
  { term: 'fuck', severity: 'severe' },
  { term: 'fucker', severity: 'severe' },
  { term: 'fucking', severity: 'severe' },
  { term: 'fuk', severity: 'severe' },
  { term: 'fck', severity: 'severe' },
  { term: 'motherfuck', severity: 'severe' },
  { term: 'motherfucker', severity: 'severe' },
  { term: 'muthafuck', severity: 'severe' },
  { term: 'mofo', severity: 'severe' },
  { term: 'shit', severity: 'severe' },
  { term: 'shite', severity: 'severe' },
  { term: 'sht', severity: 'severe' },
  { term: 'bitch', severity: 'severe' },
  { term: 'biatch', severity: 'severe' },
  { term: 'slut', severity: 'severe' },
  { term: 'whore', severity: 'severe' },
  { term: 'hoe', severity: 'severe' },
  { term: 'ho3', severity: 'severe' },
  { term: 'cunt', severity: 'severe' },
  { term: 'cnt', severity: 'severe' },
  { term: 'dick', severity: 'severe' },
  { term: 'dickhead', severity: 'severe' },
  { term: 'cock', severity: 'severe' },
  { term: 'pussy', severity: 'severe' },
  { term: 'asshole', severity: 'severe' },
  { term: 'ass hole', severity: 'severe' },
  { term: 'ahole', severity: 'severe' },
  { term: 'arsehole', severity: 'severe' },
  { term: 'bastard', severity: 'severe' },
  { term: 'fag', severity: 'severe' },
  { term: 'faggot', severity: 'severe' },
  { term: 'nigger', severity: 'severe' },
  { term: 'nigga', severity: 'severe' },
  { term: 'rape', severity: 'severe' },
  { term: 'rapist', severity: 'severe' },
  { term: 'nazi', severity: 'severe' },
  { term: 'hitler', severity: 'severe' },
  { term: 'bullshit', severity: 'medium' },
  { term: 'prick', severity: 'medium' },
  { term: 'wanker', severity: 'medium' },
  { term: 'twat', severity: 'medium' },
  { term: 'bollocks', severity: 'medium' },
  { term: 'jackass', severity: 'medium' },
  { term: 'retard', severity: 'medium' },
  { term: 'mf', severity: 'medium' },
]

const ES_TERMS: readonly ModerationTermEntry[] = [
  { term: 'puta', severity: 'severe' },
  { term: 'puto', severity: 'severe' },
  { term: 'hijodeputa', severity: 'severe' },
  { term: 'hijo de puta', severity: 'severe' },
  { term: 'hijoputa', severity: 'severe' },
  { term: 'hijaputa', severity: 'severe' },
  { term: 'tuputamadre', severity: 'severe' },
  { term: 'tu puta madre', severity: 'severe' },
  { term: 'cabron', severity: 'severe' },
  { term: 'cabrón', severity: 'severe' },
  { term: 'cabrona', severity: 'severe' },
  { term: 'gilipollas', severity: 'severe' },
  { term: 'gili', severity: 'severe' },
  { term: 'gllpoll', severity: 'severe' },
  { term: 'mierda', severity: 'severe' },
  { term: 'mrd', severity: 'severe' },
  { term: 'joder', severity: 'severe' },
  { term: 'jodete', severity: 'severe' },
  { term: 'quetejodan', severity: 'severe' },
  { term: 'que te jodan', severity: 'severe' },
  { term: 'jod', severity: 'severe' },
  { term: 'cojones', severity: 'severe' },
  { term: 'pendejo', severity: 'severe' },
  { term: 'pendeja', severity: 'severe' },
  { term: 'pendej', severity: 'severe' },
  { term: 'malparido', severity: 'severe' },
  { term: 'malparid', severity: 'severe' },
  { term: 'comemierda', severity: 'severe' },
  { term: 'come mierda', severity: 'severe' },
  { term: 'vetalamierda', severity: 'severe' },
  { term: 'vete a la mierda', severity: 'severe' },
  { term: 'vete a la m', severity: 'severe' },
  { term: 'tontodelculo', severity: 'severe' },
  { term: 'tonto del culo', severity: 'severe' },
  { term: 'tonto del c', severity: 'severe' },
  { term: 'coño', severity: 'severe' },
  { term: 'cono', severity: 'severe' },
  { term: 'maricon', severity: 'severe' },
  { term: 'maricón', severity: 'severe' },
  { term: 'verga', severity: 'severe' },
  { term: 'nazi', severity: 'severe' },
  { term: 'hitler', severity: 'severe' },
  { term: 'hostia', severity: 'medium' },
  { term: 'capullo', severity: 'medium' },
  { term: 'zorra', severity: 'medium' },
  { term: 'mamón', severity: 'medium' },
  { term: 'mamon', severity: 'medium' },
  { term: 'subnormal', severity: 'medium' },
  { term: 'retrasado', severity: 'medium' },
  { term: 'chingada', severity: 'medium' },
  { term: 'chingado', severity: 'medium' },
  { term: 'chingar', severity: 'medium' },
  { term: 'culero', severity: 'medium' },
  { term: 'culera', severity: 'medium' },
  { term: 'gonorrea', severity: 'medium' },
  { term: 'marica', severity: 'medium' },
  { term: 'pinche', severity: 'medium' },
  { term: 'carechimba', severity: 'medium' },
  { term: 'cabezadep', severity: 'medium' },
  { term: 'cabeza de pinga', severity: 'medium' },
  { term: 'cabezadp', severity: 'medium' },
]

const IT_TERMS: readonly ModerationTermEntry[] = [
  { term: 'cazzo', severity: 'severe' },
  { term: 'cazz', severity: 'severe' },
  { term: 'caz', severity: 'severe' },
  { term: 'incazzato', severity: 'severe' },
  { term: 'sticazzi', severity: 'severe' },
  { term: 'minchia', severity: 'severe' },
  { term: 'minch', severity: 'severe' },
  { term: 'merda', severity: 'severe' },
  { term: 'merd', severity: 'severe' },
  { term: 'merdaccia', severity: 'severe' },
  { term: 'stronzo', severity: 'severe' },
  { term: 'stronza', severity: 'severe' },
  { term: 'stronz', severity: 'severe' },
  { term: 'vaffanculo', severity: 'severe' },
  { term: 'vaffanc', severity: 'severe' },
  { term: 'vaffa', severity: 'severe' },
  { term: 'fanculo', severity: 'severe' },
  { term: 'coglione', severity: 'severe' },
  { term: 'coglioni', severity: 'severe' },
  { term: 'coglion', severity: 'severe' },
  { term: 'puttana', severity: 'severe' },
  { term: 'puttan', severity: 'severe' },
  { term: 'figliodiputtana', severity: 'severe' },
  { term: 'figlio di puttana', severity: 'severe' },
  { term: 'porcaputtana', severity: 'severe' },
  { term: 'porca puttana', severity: 'severe' },
  { term: 'troia', severity: 'severe' },
  { term: 'porcatroia', severity: 'severe' },
  { term: 'porca troia', severity: 'severe' },
  { term: 'pezzodimerda', severity: 'severe' },
  { term: 'pezzo di merda', severity: 'severe' },
  { term: 'porcodio', severity: 'severe' },
  { term: 'porco dio', severity: 'severe' },
  { term: 'diocane', severity: 'severe' },
  { term: 'diomerda', severity: 'severe' },
  { term: 'nazi', severity: 'severe' },
  { term: 'hitler', severity: 'severe' },
  { term: 'bastardo', severity: 'medium' },
  { term: 'figa', severity: 'medium' },
  { term: 'fica', severity: 'medium' },
  { term: 'finocchio', severity: 'medium' },
  { term: 'ricchione', severity: 'medium' },
  { term: 'testadica', severity: 'medium' },
  { term: 'testadicazzo', severity: 'medium' },
  { term: 'porco', severity: 'medium' },
  { term: 'porcod', severity: 'medium' },
  { term: 'handicapato', severity: 'medium' },
  { term: 'rompicoglioni', severity: 'medium' },
  { term: 'leccaculo', severity: 'medium' },
  { term: 'lecchino', severity: 'medium' },
]

function termsFromEntries(entries: readonly ModerationTermEntry[]): readonly string[] {
  return entries.map((entry) => entry.term)
}

export const PROFANITY_ENTRIES_BY_LOCALE: Record<ModerationLocale, readonly ModerationTermEntry[]> = {
  fr: FR_TERMS,
  en: EN_TERMS,
  es: ES_TERMS,
  it: IT_TERMS,
}

export const PROFANITY_BY_LOCALE: Record<ModerationLocale, readonly string[]> = {
  fr: termsFromEntries(FR_TERMS),
  en: termsFromEntries(EN_TERMS),
  es: termsFromEntries(ES_TERMS),
  it: termsFromEntries(IT_TERMS),
}

/** Toutes les langues actives — un pseudo est vérifié contre l'ensemble. */
export const ALL_PROFANITY_TERMS: readonly string[] = Object.values(PROFANITY_BY_LOCALE).flat()

/** Termes multi-mots stockés sans espaces, accents neutralisés. */
export function normalizeTermForMatching(term: string): string {
  return foldDiacritics(term.replace(/\s+/g, '').toLowerCase())
}

export function getTermsBySeverity(
  locale: ModerationLocale,
  severity: ModerationSeverity
): readonly string[] {
  return PROFANITY_ENTRIES_BY_LOCALE[locale]
    .filter((entry) => entry.severity === severity)
    .map((entry) => entry.term)
}
