/** Enseigne de carte à jouer — identité « Cartes sur Table ». */
export type GameSuit = 'spade' | 'heart' | 'diamond' | 'club';

export type GameMeta = {
  id: string;
  title: string;
  description: string;
  path: string;
  emoji: string;
  gradient: string;
  fallbackColor: string;
  colorFrom?: string;
  colorTo?: string;
  /**
   * Famille de jeu, exprimée en enseigne de carte :
   * ♠ rôles cachés / suspense · ♥ culture / social · ♦ hasard / dés · ♣ créa / adresse.
   */
  suit?: GameSuit;
  /** Rang affiché dans le coin de la carte (A, K, Q, J, 10…). */
  rank?: string;
  hidden?: boolean;
  onlineReady?: boolean;
  /** Jeu impossible en local (info cachée multi-écrans) : masqué du hub en mode local. */
  onlineOnly?: boolean;
  /**
   * Bornes de joueurs EN LIGNE — informatif UI (hub + lobby). La vérité côté
   * serveur vit dans `src/lib/online/game-adapters.ts` ; un test vérifie que
   * les deux restent synchronisés.
   */
  minPlayers?: number;
  maxPlayers?: number;
  /** L'hôte peut activer « compléter avec des bots » au lobby (lancer sous le minimum). */
  botsFillable?: boolean;
  /** Proposé en mode Soft (sans gorgées) — sous-ensemble des jeux onlineReady. */
  softModeReady?: boolean;
};

// Source unique de vérité pour les jeux
export const GAMES: GameMeta[] = [
  {
    id: 'monsieur-3',
    title: 'Monsieur 3',
    description: 'Un jeu de dés convivial où vous devez éviter les 3 et autres combinaisons',
    path: '/games/monsieur-3',
    emoji: '🎲',
    suit: 'diamond',
    rank: 'J',
    gradient: 'from-sky-500 to-indigo-600',
    colorFrom: '#0ea5e9',
    colorTo: '#4f46e5',
    fallbackColor: '#6366f1',
  },
  {
    id: 'pmu',
    title: 'Course PMU',
    description: 'Un jeu de paris hippiques entre amis',
    path: '/games/pmu',
    emoji: '🏇',
    suit: 'diamond',
    rank: '7',
    gradient: 'from-fuchsia-600 to-violet-700',
    colorFrom: '#c026d3',
    colorTo: '#6d28d9',
    fallbackColor: '#6366f1',
  },
  {
    id: 'petit-buveur',
    title: 'Le Petit Buveur',
    description: 'Un jeu de plateau festif avec des défis et des gorgées',
    path: '/games/petit-buveur',
    emoji: '🎲',
    suit: 'diamond',
    rank: 'A',
    gradient: 'from-emerald-600 to-teal-400',
    colorFrom: '#059669',
    colorTo: '#2dd4bf',
    fallbackColor: '#10b981',
    onlineReady: true,
    minPlayers: 2,
    maxPlayers: 99,
  },
  {
    id: 'toucher-coule',
    title: 'Toucher-Coulé',
    description: 'La bataille navale apéro en équipes : touché tu bois, coulé tu trinques !',
    path: '/games/toucher-coule',
    emoji: '🚢',
    suit: 'club',
    rank: 'Q',
    gradient: 'from-sky-600 to-cyan-400',
    colorFrom: '#0284c7',
    colorTo: '#22d3ee',
    fallbackColor: '#0ea5e9',
    onlineReady: true,
    minPlayers: 1,
    maxPlayers: 8,
    onlineOnly: true,
    softModeReady: true,
  },
  {
    id: 'menteur',
    title: 'Le Menteur',
    description: 'Dés cachés, enchères et bluff : crie « Menteur ! » au bon moment ou trinque !',
    path: '/games/menteur',
    emoji: '🎲',
    suit: 'spade',
    rank: 'J',
    gradient: 'from-orange-600 to-red-500',
    colorFrom: '#ea580c',
    colorTo: '#ef4444',
    fallbackColor: '#f97316',
    onlineReady: true,
    minPlayers: 2,
    botsFillable: true,
    maxPlayers: 6,
    onlineOnly: true,
    softModeReady: true,
  },
  {
    id: 'imposteur',
    title: "L'Imposteur",
    description: 'Un mot secret, un intrus parmi vous : indices, votes et bluff au sommet !',
    path: '/games/imposteur',
    emoji: '🕵️',
    suit: 'spade',
    rank: 'K',
    gradient: 'from-violet-600 to-fuchsia-500',
    colorFrom: '#7c3aed',
    colorTo: '#d946ef',
    fallbackColor: '#a855f7',
    onlineReady: true,
    minPlayers: 3,
    botsFillable: true,
    maxPlayers: 16,
    onlineOnly: true,
    softModeReady: true,
  },
  {
    id: 'quiz',
    title: 'Le Grand Pillaveur',
    description: 'Le quiz apéro : réponds vite et juste, ou bois ! Téléphones-buzzers et podium final.',
    path: '/games/quiz',
    emoji: '🧠',
    suit: 'heart',
    rank: 'A',
    gradient: 'from-blue-600 to-cyan-400',
    colorFrom: '#2563eb',
    colorTo: '#22d3ee',
    fallbackColor: '#3b82f6',
    onlineReady: true,
    minPlayers: 2,
    botsFillable: true,
    maxPlayers: 16,
    onlineOnly: true,
    softModeReady: true,
  },
  {
    id: 'loup-garou',
    title: 'Loup-Garou',
    description: 'Le classique des soirées, version apéro : loups, voyante, débats et lynchages qui trinquent !',
    path: '/games/loup-garou',
    emoji: '🐺',
    suit: 'spade',
    rank: 'A',
    gradient: 'from-slate-700 to-indigo-600',
    colorFrom: '#334155',
    colorTo: '#4f46e5',
    fallbackColor: '#6366f1',
    onlineReady: true,
    minPlayers: 4,
    botsFillable: true,
    maxPlayers: 12,
    onlineOnly: true,
    softModeReady: true,
  },
  {
    id: 'hi-lo',
    title: 'Hi/Lo',
    description: 'Devinez si la prochaine carte sera plus haute ou plus basse',
    path: '/games/hi-lo',
    emoji: '🃏',
    suit: 'diamond',
    rank: '10',
    gradient: 'from-rose-500 to-fuchsia-500',
    colorFrom: '#f43f5e',
    colorTo: '#d946ef',
    fallbackColor: '#f97316',
  },
  {
    id: 'purple',
    title: 'Purple',
    description: 'Pariez sur la couleur des cartes : Rouge, Noir ou Purple (alterné)',
    path: '/games/purple',
    emoji: '🟣',
    suit: 'diamond',
    rank: 'Q',
    gradient: 'from-purple-600 to-violet-500',
    colorFrom: '#9333ea',
    colorTo: '#8b5cf6',
    fallbackColor: '#a855f7',
    onlineReady: true,
    minPlayers: 2,
    maxPlayers: 16,
    botsFillable: true,
  },
  {
    id: 'pyramide',
    title: 'Pyramide',
    description: 'Retournez les cartes et progressez dans la pyramide',
    path: '/games/pyramide',
    emoji: '🔺',
    suit: 'diamond',
    rank: '9',
    gradient: 'from-amber-600 to-yellow-400',
    colorFrom: '#d97706',
    colorTo: '#facc15',
    fallbackColor: '#eab308',
  },
  {
    id: 'plinko',
    title: 'Plinko',
    description: 'Faites tomber une balle à travers des obstacles pour gagner des gorgées',
    path: '/games/plinko',
    emoji: '🔵',
    suit: 'diamond',
    rank: '8',
    gradient: 'from-emerald-500 to-lime-400',
    colorFrom: '#10b981',
    colorTo: '#a3e635',
    fallbackColor: '#22c55e',
  },
  {
    id: 'roue-des-gorgees',
    hidden: true,
    title: 'Roue des Gorgées',
    description: 'Ajoute des gorgées/actions et fais tourner la roue !',
    path: '/games/roue-des-gorgees',
    emoji: '🎡',
    gradient: 'from-pink-600 to-rose-400',
    colorFrom: '#db2777',
    colorTo: '#fb7185',
    fallbackColor: '#ec4899',
  },
  {
    id: 'ballon-surprise',
    hidden: true,
    title: 'Ballon Surprise',
    description: "Choisissez un ballon et priez pour qu'il gagne la course !",
    path: '/games/ballon-surprise',
    emoji: '🎈',
    gradient: 'from-sky-500 to-cyan-400',
    colorFrom: '#0ea5e9',
    colorTo: '#22d3ee',
    fallbackColor: '#38bdf8',
  },
  {
    id: 'petits-points',
    hidden: true,
    title: 'Petits Points',
    description: 'Un jeu de précision et de rapidité où chaque point compte !',
    path: '/games/petits-points',
    emoji: '🎯',
    gradient: 'from-indigo-600 to-blue-600',
    colorFrom: '#4f46e5',
    colorTo: '#2563eb',
    fallbackColor: '#3b82f6',
  },
  {
    id: 'pendu',
    hidden: true,
    title: 'Le Pendu des Gorgées',
    description: 'Devinez le mot mystère avant d\'être pendu ! Lettres, gorgées et suspense garantis.',
    path: '/games/pendu',
    emoji: '🎯',
    gradient: 'from-purple-600 to-indigo-600',
    colorFrom: '#7c3aed',
    colorTo: '#4f46e5',
    fallbackColor: '#6366f1',
  },
  {
    id: 'trial-poursuite',
    hidden: true,
    title: 'Trial Poursuite',
    description: 'Redez des défis fous sous pression ! Coordination, créativité et rapidité au programme.',
    path: '/games/trial-poursuite',
    emoji: '🏍️',
    gradient: 'from-red-600 to-orange-500',
    colorFrom: '#dc2626',
    colorTo: '#f97316',
    fallbackColor: '#ef4444',
  },
  {
    id: '1220',
    title: '1220',
    description:
      'Un dé 12 et un dé 20 : pariez sur la parité, une plage de somme, et deux chiffres clés pour boire ou faire boire.',
    path: '/games/1220',
    emoji: '🎲',
    suit: 'diamond',
    rank: 'K',
    gradient: 'from-violet-600 to-amber-500',
    colorFrom: '#7c3aed',
    colorTo: '#f59e0b',
    fallbackColor: '#a855f7',
    onlineReady: true,
    minPlayers: 2,
    maxPlayers: 16,
    botsFillable: true,
  },
  {
    id: 'bluff',
    title: 'Le Grand Bluff',
    description:
      'Une question, une fausse réponse à inventer, et un vote parmi les bluffs : trouve la vraie ou trompe tout le monde !',
    path: '/games/bluff',
    emoji: '🃏',
    suit: 'heart',
    rank: 'K',
    gradient: 'from-rose-600 to-amber-500',
    colorFrom: '#e11d48',
    colorTo: '#f59e0b',
    fallbackColor: '#f43f5e',
    onlineReady: true,
    minPlayers: 3,
    maxPlayers: 16,
    onlineOnly: true,
    botsFillable: true,
    softModeReady: true,
  },
  {
    id: 'espion',
    title: "Qui est l'Espion ?",
    description:
      "Un lieu secret, un espion qui ne sait rien : questionnez-vous, accusez, ou devinez le lieu avant la fin du temps imparti !",
    path: '/games/espion',
    emoji: '🕵️',
    suit: 'spade',
    rank: 'Q',
    gradient: 'from-slate-700 to-cyan-600',
    colorFrom: '#334155',
    colorTo: '#0891b2',
    fallbackColor: '#0e7490',
    onlineReady: true,
    minPlayers: 3,
    maxPlayers: 16,
    onlineOnly: true,
    botsFillable: true,
    softModeReady: true,
  },
  {
    id: 'tabou',
    title: 'Tabou Vocal',
    description:
      'Décris un mot à voix haute sans prononcer les 4 mots tabous : ton équipe devine, les adversaires guettent la faute !',
    path: '/games/tabou',
    emoji: '🤐',
    suit: 'heart',
    rank: 'Q',
    gradient: 'from-emerald-600 to-teal-500',
    colorFrom: '#059669',
    colorTo: '#14b8a6',
    fallbackColor: '#10b981',
    onlineReady: true,
    minPlayers: 4,
    maxPlayers: 16,
    onlineOnly: true,
    botsFillable: true,
    softModeReady: true,
  },
  {
    id: 'crobard',
    title: 'Crobard',
    description:
      "Choisis un mot, dessine-le en direct sur l'écran : premier qui devine marque gros, le dessinateur aussi !",
    path: '/games/crobard',
    emoji: '🎨',
    suit: 'club',
    rank: 'A',
    gradient: 'from-fuchsia-600 to-orange-500',
    colorFrom: '#c026d3',
    colorTo: '#f97316',
    fallbackColor: '#e11d48',
    onlineReady: true,
    minPlayers: 3,
    maxPlayers: 16,
    onlineOnly: true,
    botsFillable: true,
    softModeReady: true,
  },
  {
    id: 'sans-filtre',
    title: 'Sans Filtre',
    description:
      'Une carte à trou, des réponses de mauvaise foi : le juge du tour couronne la plus drôle. À lire à voix haute !',
    path: '/games/sans-filtre',
    emoji: '🃏',
    suit: 'club',
    rank: 'J',
    gradient: 'from-zinc-800 to-amber-600',
    colorFrom: '#27272a',
    colorTo: '#d97706',
    fallbackColor: '#b45309',
    onlineReady: true,
    minPlayers: 4,
    maxPlayers: 16,
    onlineOnly: true,
    botsFillable: true,
    softModeReady: true,
  },
  {
    id: 'mots-codes',
    title: 'Mots Codés',
    description:
      'Deux équipes, 25 mots, un Maître-mot par camp : un indice, un nombre, et gare à l’assassin !',
    path: '/games/mots-codes',
    emoji: '🗝️',
    suit: 'heart',
    rank: 'J',
    gradient: 'from-amber-600 to-red-700',
    colorFrom: '#d97706',
    colorTo: '#b91c1c',
    fallbackColor: '#b45309',
    onlineReady: true,
    minPlayers: 4,
    maxPlayers: 16,
    onlineOnly: true,
    softModeReady: true,
  },
  {
    id: 'dilemmes',
    title: 'Dilemmes',
    description:
      'Tu préfères, Je n’ai jamais, Qui de la table : votes secrets révélés d’un coup — la minorité trinque !',
    path: '/games/dilemmes',
    emoji: '⚖️',
    suit: 'heart',
    rank: '9',
    gradient: 'from-rose-700 to-amber-600',
    colorFrom: '#be123c',
    colorTo: '#d97706',
    fallbackColor: '#be123c',
    onlineReady: true,
    minPlayers: 3,
    maxPlayers: 16,
    onlineOnly: true,
    botsFillable: true,
    softModeReady: true,
  },
  {
    id: 'petit-bac',
    title: 'Petit Bac',
    description:
      'Une lettre, cinq catégories : le premier qui remplit tout crie STOP. Réponses uniques 2 pts, doublons 1 pt — contestez à la révélation !',
    path: '/games/petit-bac',
    emoji: '📝',
    suit: 'heart',
    rank: '10',
    gradient: 'from-sky-700 to-amber-600',
    colorFrom: '#0369a1',
    colorTo: '#d97706',
    fallbackColor: '#0369a1',
    onlineReady: true,
    minPlayers: 2,
    maxPlayers: 16,
    onlineOnly: true,
    softModeReady: true,
  },
  {
    id: 'telephone-dessine',
    title: 'Téléphone Dessiné',
    description:
      "Écris une phrase, le suivant la dessine, le suivant la devine... jusqu'au fou rire collectif en fin de partie !",
    path: '/games/telephone-dessine',
    emoji: '📞',
    suit: 'club',
    rank: 'K',
    gradient: 'from-teal-600 to-indigo-500',
    colorFrom: '#0d9488',
    colorTo: '#6366f1',
    fallbackColor: '#14b8a6',
    onlineReady: true,
    minPlayers: 3,
    maxPlayers: 8,
    onlineOnly: true,
    softModeReady: true,
  },
];

export function getGameById(id: string): GameMeta | undefined {
  return GAMES.find(g => g.id === id);
}



